<a href="https://colab.research.google.com/github/patoowp13/patricio-marrone/blob/main/practica_avanzada_coder2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DataSet Flights 🛬**

In [ ]:
import pandas as pd
flight = pd.read_csv('flight_nb.csv')
flight.head()

flight_number        airline_name             departure_airport  \
0        IB4174              Iberia  Adolfo Suárez Madrid–Barajas   
1        NH6825  All Nippon Airways                        Haneda   
2        BA7908     British Airways                      Heathrow   
3        EK8320            Emirates           Dubai International   
4        SQ8449  Singapore Airlines                        Changi   

  departure_city departure_country departure_time             arrival_airport  \
0         Bussum       Netherlands       12:35 AM           Charles de Gaulle   
1      Manjacaze        Mozambique        8:58 AM  Kuala Lumpur International   
2          Junín         Argentina       10:33 AM           Charles de Gaulle   
3        Kukuluk         Indonesia        4:37 PM         Hamad International   
4          Bukor            Serbia        6:32 AM         Cairo International   

  arrival_city arrival_country  duration_hours           pilot_name  \
0  Miandrarivo      Madagascar           13.44        Raven Halbard   
1    Chengjiao           China            9.85       Lorri Dashwood   
2     Zabłocie          Poland           22.69        Brion Forster   
3  Castanheira        Portugal           12.72       Benni Yegoshin   
4  Villa Verde     Philippines            1.69  Stephine Messenbird   

       co_pilot_name  passenger_count  cargo_weight  fuel_capacity  \
0      Haskel Treace            327.0        146.17         313.34   
1   Francklyn Rojahn             94.0        454.40        9978.58   
2       Arielle Yate            349.0        281.57        6902.25   
3  Benyamin Claworth            279.0        130.55        6981.69   
4    Tabbitha Melsom            359.0        204.55        8182.71   

   departure_gate  arrival_gate flight_status  ticket_price  
0             6.0          13.0       delayed       8962.25  
1            12.0          12.0       delayed       3021.94  
2            11.0           1.0     cancelled       3592.14  
3            16.0           7.0       on-time       9498.40  
4             5.0          13.0     cancelled       5840.09

*Promedio de horas de vuelo y desvio estandar.*




In [ ]:
import pandas as pd
flight = pd.read_csv('flight_nb.csv')
import numpy as np
mean_dhour = np.mean(flight['duration_hours'])
print("mean duration hours flight:",mean_dhour)
std_dhour = np.std(flight['duration_hours'])
print("desviation standard duration hours flight:",std_dhour)

mean duration hours flight: 12.711084999999999
desviation standard duration hours flight: 6.710995959824075


*Filtrado por horas de vuelo*

In [ ]:
half_day= flight[flight['duration_hours']>=12]
half_day.head()

flight_number      airline_name             departure_airport  \
0        IB4174            Iberia  Adolfo Suárez Madrid–Barajas   
2        BA7908   British Airways                      Heathrow   
3        EK8320          Emirates           Dubai International   
6        SK9763  SAS Scandinavian            Copenhagen Airport   
7        AI3868         Air India   Indira Gandhi International   

  departure_city departure_country departure_time  \
0         Bussum       Netherlands       12:35 AM   
2          Junín         Argentina       10:33 AM   
3        Kukuluk         Indonesia        4:37 PM   
6      San Diego          Colombia        5:19 AM   
7        Taiping             China        9:00 PM   

                     arrival_airport arrival_city arrival_country  \
0                  Charles de Gaulle  Miandrarivo      Madagascar   
2                  Charles de Gaulle     Zabłocie          Poland   
3                Hamad International  Castanheira        Portugal   
6                  Charles de Gaulle       Corona   United States   
7  Chhatrapati Shivaji International   Joypur Hāt      Bangladesh   

   duration_hours      pilot_name      co_pilot_name  passenger_count  \
0           13.44   Raven Halbard      Haskel Treace            327.0   
2           22.69   Brion Forster       Arielle Yate            349.0   
3           12.72  Benni Yegoshin  Benyamin Claworth            279.0   
6           19.44  Ardyth Archell       Mandi Joiner            247.0   
7           20.25  Mick Telezhkin     Devina Trammel            377.0   

   cargo_weight  fuel_capacity  departure_gate  arrival_gate flight_status  \
0        146.17         313.34             6.0          13.0       delayed   
2        281.57        6902.25            11.0           1.0     cancelled   
3        130.55        6981.69            16.0           7.0       on-time   
6         66.15        1940.24             6.0          12.0       on-time   
7        333.05        5788.54            10.0           8.0       delayed   

   ticket_price  
0       8962.25  
2       3592.14  
3       9498.40  
6       6452.65  
7       7471.09

*Filtrado por gastos del ticket*

In [ ]:
expensive_ticket = flight[flight["ticket_price"]>=4000]
print("Cantidad de ticket que superan los 4000 usd:",expensive_ticket["ticket_price"].count())

Cantidad de ticket que superan los 4000 usd: 1209


*Ingresos y promedio de gastos en vuelos por país*

In [ ]:
precio_destino = flight.groupby("departure_country")["ticket_price"].agg(['mean'])
print("Top 10 países con mayor promedio del valor del ticket :",precio_destino.sort_values(by='mean', ascending=False).head(10))

Top 10 países con mayor promedio del valor del ticket :                                       mean
departure_country                         
Namibia                           9937.000
American Samoa                    9797.000
Madagascar                        9466.270
Martinique                        9417.280
Oman                              9189.910
Democratic Republic of the Congo  9119.500
French Polynesia                  9029.000
Ecuador                           9021.845
Qatar                             8913.500
Paraguay                          8551.020


*Llenar valores nulos de columnas*

In [ ]:
fillna0= flight.fillna(0)
print(fillna0)
fill_mean= flight["fuel_capacity"].fillna(flight["fuel_capacity"].mean())
print(fill_mean)


     flight_number        airline_name             departure_airport  \
0           IB4174              Iberia  Adolfo Suárez Madrid–Barajas   
1           NH6825  All Nippon Airways                        Haneda   
2           BA7908     British Airways                      Heathrow   
3           EK8320            Emirates           Dubai International   
4           SQ8449  Singapore Airlines                        Changi   
...            ...                 ...                           ...   
1996        LH6645           Lufthansa             Frankfurt Airport   
1997        NZ7915     Air New Zealand              Auckland Airport   
1998        SK4327    SAS Scandinavian            Copenhagen Airport   
1999        SK4970    SAS Scandinavian            Copenhagen Airport   
2000             0                   0                             0   

     departure_city departure_country departure_time  \
0            Bussum       Netherlands       12:35 AM   
1         Manjacaze    

**Practica Numpy**

In [ ]:
import numpy as np
array_uni = np.array([1, 2, 3, 4, 5])
print(array_uni)

[1 2 3 4 5]


In [ ]:
array_multi = np.array([[45, 12, 345], [4, 5, 6]])
print(array_multi)

[[ 45  12 345]
 [  4   5   6]]


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
arrsupr = np.concatenate((arr1,arr2))
print(arrsupr)
arr = np.arange(8)
arrsplit = np.split(arr,2)
print(arrsplit)
arrmult= np.multiply(arr1,arr2)
print(arrmult)
arr_concat= np.concatenate((arr1,arr2))
print(arr_concat)



[ 1  2  3  4  5  6  7  8  9 10]
[array([0, 1, 2, 3]), array([4, 5, 6, 7])]
[ 6 14 24 36 50]
[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
zeros = np.zeros((4,5))
ones = np.ones(4)
full = np.full(4,15458)
print(zeros)
print(ones)
print(full)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1. 1.]
[15458 15458 15458 15458]


In [ ]:
random_num = np.random.randint(50,100,size=20)
print("random num:",random_num)
mean_random= np.mean(random_num)
print("mean random:",mean_random)
median_random=np.median(random_num)
print("median random:",median_random)

random num: [92 80 96 74 58 60 92 69 85 96 95 62 92 69 65 76 76 89 70 75]
mean random: 78.55
median random: 76.0


In [ ]:
import pandas as pd
numeros= [12,44,58,55,124,68]
serie_numeros= pd.Series(numeros)
print(serie_numeros)

0     12
1     44
2     58
3     55
4    124
5     68
dtype: int64


In [ ]:
datos = {'a':1,'b':2,'c':3,'d': 4,'e': 5}
serie_datos = pd.Series(datos)
print(serie_datos)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
LaData = [[1,'roberto','pistola','adicto'],[3,'adalberto','no','trabjador'],[0,'asturio','cuchillo','alcohilico']]
columna = ['causas','nombre','arma','actividad']
Personas = pd.DataFrame(LaData, columns=columna)
Personas = Personas.set_index('nombre')
print(Personas)

           causas      arma   actividad
nombre                                 
roberto         1   pistola      adicto
adalberto       3        no   trabjador
asturio         0  cuchillo  alcohilico


In [ ]:
flight['departure_country'] = flight['departure_country'].str.replace('United States', 'USA')
print(flight[flight['departure_country'] == 'USA'].head())

    flight_number        airline_name          departure_airport  \
67         UA3770     United Airlines  Los Angeles International   
70         QF1344              Qantas             Sydney Airport   
105        SQ7786  Singapore Airlines                     Changi   
110        EK5144            Emirates        Dubai International   
150        UA7729     United Airlines  Los Angeles International   

    departure_city departure_country departure_time  \
67      Youngstown               USA        7:54 AM   
70     New Orleans               USA       11:49 AM   
105     Great Neck               USA        9:20 AM   
110    Los Angeles               USA       10:08 AM   
150         Toledo               USA        2:21 AM   

                   arrival_airport arrival_city arrival_country  \
67             Cairo International     Khanabad     Afghanistan   
70               Melbourne Airport     Richmond   United States   
105  Beijing Capital International       Sofifi       Indon