<a href="https://colab.research.google.com/github/patoowp13/patricio-marrone/blob/main/practica_coder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data set Flights 🛬**

In [ ]:
import pandas as pd
flight = pd.read_csv('flight_nb.csv')
flight.head()

flight_number        airline_name             departure_airport  \
0        IB4174              Iberia  Adolfo Suárez Madrid–Barajas   
1        NH6825  All Nippon Airways                        Haneda   
2        BA7908     British Airways                      Heathrow   
3        EK8320            Emirates           Dubai International   
4        SQ8449  Singapore Airlines                        Changi   

  departure_city departure_country departure_time             arrival_airport  \
0         Bussum       Netherlands       12:35 AM           Charles de Gaulle   
1      Manjacaze        Mozambique        8:58 AM  Kuala Lumpur International   
2          Junín         Argentina       10:33 AM           Charles de Gaulle   
3        Kukuluk         Indonesia        4:37 PM         Hamad International   
4          Bukor            Serbia        6:32 AM         Cairo International   

  arrival_city arrival_country  duration_hours           pilot_name  \
0  Miandrarivo      Madagascar           13.44        Raven Halbard   
1    Chengjiao           China            9.85       Lorri Dashwood   
2     Zabłocie          Poland           22.69        Brion Forster   
3  Castanheira        Portugal           12.72       Benni Yegoshin   
4  Villa Verde     Philippines            1.69  Stephine Messenbird   

       co_pilot_name  passenger_count  cargo_weight  fuel_capacity  \
0      Haskel Treace            327.0        146.17         313.34   
1   Francklyn Rojahn             94.0        454.40        9978.58   
2       Arielle Yate            349.0        281.57        6902.25   
3  Benyamin Claworth            279.0        130.55        6981.69   
4    Tabbitha Melsom            359.0        204.55        8182.71   

   departure_gate  arrival_gate flight_status  ticket_price  
0             6.0          13.0       delayed       8962.25  
1            12.0          12.0       delayed       3021.94  
2            11.0           1.0     cancelled       3592.14  
3            16.0           7.0       on-time       9498.40  
4             5.0          13.0     cancelled       5840.09

*Promedio de horas de vuelo.*

In [ ]:
import pandas as pd
flight = pd.read_csv('flight_nb.csv')
import numpy as np
mean_dhour = np.mean(flight['duration_hours'])
print(mean_dhour)

12.711084999999999


*Standard Desviation horas de vuelo*




In [ ]:
std_dhour = np.std(flight['duration_hours'])
print(std_dhour)

6.710995959824075


**Practica Numpy**

In [ ]:
import numpy as np
array_uni = np.array([1, 2, 3, 4, 5])
print(array_uni)

[1 2 3 4 5]


In [ ]:
array_multi = np.array([[45, 12, 345], [4, 5, 6]])
print(array_multi)

[[ 45  12 345]
 [  4   5   6]]


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 7, 8, 9, 10])
arrsupr = np.concatenate((arr1,arr2))
print(arrsupr)
arr = np.arange(8)
arrsplit = np.split(arr,2)
print(arrsplit)
arrmult= np.multiply(arr1,arr2)
print(arrmult)


[ 1  2  3  4  5  1  7  8  9 10]
[array([0, 1, 2, 3]), array([4, 5, 6, 7])]
[ 1 14 24 36 50]


In [ ]:
zeros = np.zeros((4,5))
ones = np.ones(4)
full = np.full(4,15458)
print(zeros)
print(ones)
print(full)